### ISSUE TITLE
User login component

### ISSUE THREAD

**Issue by KeijoTomiste** [school-stuff/oop-projekt#7]
Have a rendering component that has an input (for name) and a submit button. Once submit have been pressed, should send data to service handling communication with server, should wait until server tells it got the info and then remove self from being rendered. (Bonus points for not allowing submit being pressed while query in flight)

**Comment by TaliKert** [comment]
Ei mõtle välja, kus tuleks socket avada, et selle sulgemist hiljem ilusti manage'ida ning et iga kõrvalklass saaks seda kasutada. Tuleks kuidagi Client klassi viia ning kogu kompott seal ühe try-with-resourcesi sisse toppida?

**Comment by KeijoTomiste** [comment]
Kujutan ise ette, et socket-t me ise kinni ei panegi, tahame et kogu aeg oleks ühendus ja et server saaks meile ka andmeid saata kui soovib ([loe lisaks](https://www.pubnub.com/blog/2015-01-05-websockets-vs-rest-api-understanding-the-difference/)). Selleks et aga uut socketit iga kord ei tee, tuleks teha eraldi singleton class (intellij-s kui uut teed, siis `kind` pane `singleton`, siis teeb ise valmis loogika). Ainus juhus, kui tahamegi et socket kinni läheks, on siis kui app kinni pannakse. Võid uurida, kas selle jaoks peame ise socketi kinni panema v  kuna app lõpetab töö, siis läheb socket ise kinni. Kui ei panda, siis võid teha eraldi func, mis manuaalselt sulgeb socketi. 

Lisaks, mujalt ei tohiks socketit kätte saada, loogika kuidas suheldakse peaks olema selles classis ja teised klassid kutsuvad mingeid funktsioone (nt `saveUser`), mis siis vajadusel parsib andmed õigele kujule ja saadab edasi läbi socketi. Socketile ei tohi just sellepärast ligi saada, et me ei taha, et iga service kasutaks andmete saatmiseks erinevat loogikat ja kui kunagi tahaks muuta, kuidas andmeid saadame, siis me ei peaks seda muutma mitmest kohast.

Paar näidet:
```
public class SingletonClass {
    private static SingletonClass ourInstance = new SingletonClass();
    
    private Socket socket;

    public static SingletonClass getInstance() {
        return ourInstance;
    }

    private SingletonClass() {
        // Socket tuleks kohe alguses valmis teha ja kindlustada et alati olemas
        initSocket();
    }

    // Võiks private olla aga kuna `kill` on, siis peaks uut ka teha saama
    public void initSocket() {
        socket = new Socket();
    }

    // Kui ongi vaja kinni panna
    public void killSocket() {
        socket.close();
        socket = null;
    }
}
```

```
    // Iga query jaoks mingi func
    public void mingiQuery(MyDataThingie myDataThingie) {
        myDataThingie.maybeDoSmthWithIt;
        sendData(myDataThingie);
    }
    
    // Eraldi generic func mida iga andme saatja kutsub
    private void sendData(MyDataThingie myDataThingie) {
        // Siin võib nt kontrollida kas socket veel avatud ja kui ei ole avab uue vms
        try (PrintWriter out = new PrintWriter(socket.getOutputStream(), true)) {
            out.println(myDataThingie);
        }
    }
    
    // Küllap mingi func mis peaks pidevalt vaatama kas midagi serverist tuli
    // Vast hea välja kutsuda constructoris ja eraldi threadi peal vaatab ja 
    // töötab
    private void recieveData() {
        try (PrintWriter in = new PrintWriter(socket.getOutputStream(), true);
             BufferedReader stdIn = new BufferedReader(new InputStreamReader(System.in))) {
            // Parse input and call corresponding func
        }
    }
```
